### ISSUE TITLE
createPost 모달창 UI 수정

### ISSUE THREAD

**Issue by happydoeun** [kimdovi-dev/Airtravel999#71]
- [x] 위치 및 사이즈 조정 
- [x] 여행지 select box 를 입력창으로 수정 
- [x] 게시글 타이틀 창 추가
- [x] 첨부파일 뱃지 추가

**Comment by happydoeun** [comment]
@suyeonpi 수연님 요거 맞나여? 여행지도 입력창으로 바꾸고 제목 입력창도 새로 추가해야 되는 것 맞죵??

**Comment by suyeonpi** [comment]
네 맞아요!! 👍

2021년 11월 4일 (목) 오후 8:33, Kim doeun ***@***.***>님이 작성:
